//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jubahbapak
{
    using System;
    using System.Collections.Generic;
    
    public partial class image_table
    {
        public int imageID { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string altText { get; set; }
        public string extension { get; set; }
        public string imgName { get; set; }
        public string prevImg1 { get; set; }
        public Nullable<int> width1 { get; set; }
        public Nullable<int> height1 { get; set; }
        public string altText1 { get; set; }
        public string extension1 { get; set; }
        public string prevImg2 { get; set; }
        public Nullable<int> width2 { get; set; }
        public Nullable<int> height2 { get; set; }
        public string altText2 { get; set; }
        public string extension2 { get; set; }
        public string prevImg3 { get; set; }
        public Nullable<int> width3 { get; set; }
        public Nullable<int> height3 { get; set; }
        public string altText3 { get; set; }
        public string extension3 { get; set; }
        public string featureImg { get; set; }
        public Nullable<int> fimgwidth { get; set; }
        public Nullable<int> fimgheight { get; set; }
        public string fimgaltText { get; set; }
        public string fimgextension { get; set; }
    }
}
