//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jubahbapak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class co5027Entities : DbContext
    {
        public co5027Entities()
            : base("name=co5027Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<prod_table> prod_table { get; set; }
        public virtual DbSet<image_table> image_table { get; set; }
        public virtual DbSet<prevImage1_table> prevImage1_table { get; set; }
        public virtual DbSet<prevImage2_table> prevImage2_table { get; set; }
    }
}
