//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jubahbapak
{
    using System;
    using System.Collections.Generic;
    
    public partial class prevImage2_table
    {
        public int prevImg2 { get; set; }
        public Nullable<int> width2 { get; set; }
        public Nullable<int> height2 { get; set; }
        public string altText2 { get; set; }
        public string extension { get; set; }
        public string prevImg2Name { get; set; }
    }
}
