//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jubahbapak
{
    using System;
    using System.Collections.Generic;
    
    public partial class prevImage1_table
    {
        public int prevImg1 { get; set; }
        public Nullable<int> width1 { get; set; }
        public Nullable<int> height { get; set; }
        public string altText1 { get; set; }
        public string extension1 { get; set; }
        public string prevImg3Name { get; set; }
    }
}
