//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jubahbapak
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_table
    {
        public int id { get; set; }
        public string prod_name { get; set; }
        public string prod_details { get; set; }
        public string prod_price { get; set; }
        public Nullable<int> prod_quantity { get; set; }
        public string onSale { get; set; }
        public string onFeatured { get; set; }
    }
}
