//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jubahbapak
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int imageID { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string altText { get; set; }
        public string extension { get; set; }
        public string imgName { get; set; }
    }
}
